# Generated by Django 4.2 on 2023-04-19 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersaccess', '0002_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_field', models.CharField(max_length=255)),
                ('my_field_hash', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
    ]
