# Generated by Django 4.2 on 2023-04-19 11:48

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('usersaccess', '0005_historicaltestchange_excutor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltestchange',
            name='my_field',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='testchange',
            name='my_field',
            field=tinymce.models.HTMLField(),
        ),
    ]
