# Generated by Django 4.2 on 2023-04-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersaccess', '0006_alter_historicaltestchange_my_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltestchange',
            name='dc_image',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='testchange',
            name='dc_image',
            field=models.ImageField(blank=True, null=True, upload_to='deathCertificates/'),
        ),
    ]
