# Generated by Django 4.2 on 2023-04-23 14:22

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('usersaccess', '0007_historicaltestchange_dc_image_testchange_dc_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltestchange',
            name='my_field',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testchange',
            name='my_field',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
