# Generated by Django 4.2 on 2023-04-26 10:03

from django.db import migrations, models
import usersaccess.models


class Migration(migrations.Migration):

    dependencies = [
        ('usersaccess', '0009_historicaltestchange_dc_pdf_testchange_dc_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testchange',
            name='dc_image',
            field=models.ImageField(blank=True, null=True, upload_to=usersaccess.models.upload_to),
        ),
        migrations.AlterField(
            model_name='testchange',
            name='dc_pdf',
            field=models.FileField(blank=True, null=True, upload_to=usersaccess.models.upload_to),
        ),
    ]
