# Generated by Django 4.2 on 2023-04-26 10:22

from django.db import migrations, models
import usersaccess.models


class Migration(migrations.Migration):

    dependencies = [
        ('usersaccess', '0010_alter_testchange_dc_image_alter_testchange_dc_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltestchange',
            name='will_pdf',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='testchange',
            name='will_pdf',
            field=models.FileField(blank=True, null=True, upload_to=usersaccess.models.upload_to),
        ),
    ]
