# Generated by Django 4.2 on 2023-04-26 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersaccess', '0011_historicaltestchange_will_pdf_testchange_will_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltestchange',
            name='emails',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testchange',
            name='emails',
            field=models.TextField(blank=True, null=True),
        ),
    ]
