# Generated by Django 4.2 on 2023-04-28 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersaccess', '0013_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltestchange',
            name='executor_sign',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicaltestchange',
            name='lawyer_sign',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicaltestchange',
            name='will_owner_sign',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='testchange',
            name='executor_sign',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='testchange',
            name='lawyer_sign',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='testchange',
            name='will_owner_sign',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
