# Generated by Django 4.2 on 2023-04-30 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersaccess', '0014_historicaltestchange_executor_sign_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltestchange',
            name='dc_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testchange',
            name='dc_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
